-- Matches table INSERT statements for production
-- Run this SQL directly in your production database
-- First, clear existing data (optional - uncomment if needed)
-- TRUNCATE TABLE matches;
-- Male matches
INSERT INTO matches (
        jornada,
        date,
        time,
        local_team,
        visitor_team,
        court,
        result,
        category,
        created_at,
        updated_at
    )
VALUES -- Jornada 1
    (
        1,
        '2025-11-29',
        NULL,
        'ELITEFIT CANARIAS',
        'BRAVEHEART GC',
        'Canteras',
        '0-3',
        'male',
        NOW(),
        NOW()
    ),
    (
        1,
        '2025-11-29',
        NULL,
        'NET 7 BLACKBOARD',
        'CANACANTE',
        'Alcaravaneras',
        '1-2',
        'male',
        NOW(),
        NOW()
    ),
    (
        1,
        '2025-11-29',
        NULL,
        'DESCANSA',
        'VOLEY MAXORATA',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        1,
        '2025-11-29',
        NULL,
        'ICOREN',
        'OVERBLOCK MASPALOMAS',
        'tenerife',
        '3-0',
        'male',
        NOW(),
        NOW()
    ),
    -- Jornada 2
    (
        2,
        '2025-12-13',
        NULL,
        'BRAVEHEART GC',
        'OVERBLOCK MASPALOMAS',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        2,
        '2025-12-13',
        NULL,
        'VOLEY MAXORATA',
        'ICOREN',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        2,
        '2025-12-14',
        '10:00',
        'CANACANTE',
        'DESCANSA',
        'Canteras',
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        2,
        '2025-12-13',
        NULL,
        'ELITEFIT CANARIAS',
        'NET 7 BLACKBOARD',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    -- Jornada 3
    (
        3,
        '2025-12-27',
        NULL,
        'NET 7 BLACKBOARD',
        'BRAVEHEART GC',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        3,
        '2025-12-27',
        NULL,
        'DESCANSA',
        'ELITEFIT CANARIAS',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        3,
        '2025-12-27',
        NULL,
        'ICOREN',
        'CANACANTE',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        3,
        '2025-12-27',
        NULL,
        'OVERBLOCK MASPALOMAS',
        'VOLEY MAXORATA',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    -- Jornada 4
    (
        4,
        '2026-01-03',
        NULL,
        'BRAVEHEART GC',
        'VOLEY MAXORATA',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        4,
        '2026-01-04',
        '10:00',
        'CANACANTE',
        'OVERBLOCK MASPALOMAS',
        'Canteras',
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        4,
        '2026-01-03',
        NULL,
        'ELITEFIT CANARIAS',
        'ICOREN',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        4,
        '2026-01-03',
        NULL,
        'NET 7 BLACKBOARD',
        'DESCANSA',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    -- Jornada 5
    (
        5,
        '2026-01-10',
        NULL,
        'DESCANSA',
        'BRAVEHEART GC',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        5,
        '2026-01-10',
        NULL,
        'ICOREN',
        'NET 7 BLACKBOARD',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        5,
        '2026-01-10',
        NULL,
        'OVERBLOCK MASPALOMAS',
        'ELITEFIT CANARIAS',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        5,
        '2026-01-10',
        NULL,
        'VOLEY MAXORATA',
        'CANACANTE',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    -- Jornada 6
    (
        6,
        '2026-01-17',
        NULL,
        'BRAVEHEART GC',
        'CANACANTE',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        6,
        '2026-01-17',
        NULL,
        'ELITEFIT CANARIAS',
        'VOLEY MAXORATA',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        6,
        '2026-01-17',
        NULL,
        'NET 7 BLACKBOARD',
        'OVERBLOCK MASPALOMAS',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        6,
        '2026-01-17',
        NULL,
        'DESCANSA',
        'ICOREN',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    -- Jornada 7
    (
        7,
        '2026-01-24',
        NULL,
        'ICOREN',
        'BRAVEHEART GC',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        7,
        '2026-01-24',
        NULL,
        'OVERBLOCK MASPALOMAS',
        'DESCANSA',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        7,
        '2026-01-24',
        NULL,
        'VOLEY MAXORATA',
        'NET 7 BLACKBOARD',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        7,
        '2026-01-25',
        '10:00',
        'CANACANTE',
        'ELITEFIT CANARIAS',
        'Canteras',
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    -- Jornada 8
    (
        8,
        '2026-02-07',
        NULL,
        'BRAVEHEART GC',
        'ELITEFIT CANARIAS',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        8,
        '2026-02-08',
        '10:00',
        'CANACANTE',
        'NET 7 BLACKBOARD',
        'Canteras',
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        8,
        '2026-02-07',
        NULL,
        'VOLEY MAXORATA',
        'DESCANSA',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        8,
        '2026-02-07',
        NULL,
        'OVERBLOCK MASPALOMAS',
        'ICOREN',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    -- Jornada 9
    (
        9,
        '2026-02-14',
        NULL,
        'OVERBLOCK MASPALOMAS',
        'BRAVEHEART GC',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        9,
        '2026-02-14',
        NULL,
        'ICOREN',
        'VOLEY MAXORATA',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        9,
        '2026-02-14',
        NULL,
        'DESCANSA',
        'CANACANTE',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        9,
        '2026-02-14',
        NULL,
        'NET 7 BLACKBOARD',
        'ELITEFIT CANARIAS',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    -- Jornada 10
    (
        10,
        '2026-02-28',
        NULL,
        'BRAVEHEART GC',
        'NET 7 BLACKBOARD',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        10,
        '2026-02-28',
        NULL,
        'ELITEFIT CANARIAS',
        'DESCANSA',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        10,
        '2026-03-01',
        '10:00',
        'CANACANTE',
        'ICOREN',
        'Canteras',
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        10,
        '2026-02-28',
        NULL,
        'VOLEY MAXORATA',
        'OVERBLOCK MASPALOMAS',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    -- Jornada 11
    (
        11,
        '2026-03-07',
        NULL,
        'VOLEY MAXORATA',
        'BRAVEHEART GC',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        11,
        '2026-03-07',
        NULL,
        'OVERBLOCK MASPALOMAS',
        'CANACANTE',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        11,
        '2026-03-07',
        NULL,
        'ICOREN',
        'ELITEFIT CANARIAS',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        11,
        '2026-03-07',
        NULL,
        'DESCANSA',
        'NET 7 BLACKBOARD',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    -- Jornada 12
    (
        12,
        '2026-03-21',
        NULL,
        'BRAVEHEART GC',
        'DESCANSA',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        12,
        '2026-03-21',
        NULL,
        'NET 7 BLACKBOARD',
        'ICOREN',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        12,
        '2026-03-21',
        NULL,
        'ELITEFIT CANARIAS',
        'OVERBLOCK MASPALOMAS',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        12,
        '2026-03-22',
        '10:00',
        'CANACANTE',
        'VOLEY MAXORATA',
        'Canteras',
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    -- Jornada 13
    (
        13,
        '2026-03-29',
        '10:00',
        'CANACANTE',
        'BRAVEHEART GC',
        'Canteras',
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        13,
        '2026-03-28',
        NULL,
        'VOLEY MAXORATA',
        'ELITEFIT CANARIAS',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        13,
        '2026-03-28',
        NULL,
        'OVERBLOCK MASPALOMAS',
        'NET 7 BLACKBOARD',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        13,
        '2026-03-28',
        NULL,
        'ICOREN',
        'DESCANSA',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    -- Jornada 14
    (
        14,
        '2026-04-11',
        NULL,
        'BRAVEHEART GC',
        'ICOREN',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        14,
        '2026-04-11',
        NULL,
        'DESCANSA',
        'OVERBLOCK MASPALOMAS',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        14,
        '2026-04-11',
        NULL,
        'NET 7 BLACKBOARD',
        'VOLEY MAXORATA',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    ),
    (
        14,
        '2026-04-11',
        NULL,
        'ELITEFIT CANARIAS',
        'CANACANTE',
        NULL,
        NULL,
        'male',
        NOW(),
        NOW()
    );
-- Female matches
INSERT INTO matches (
        jornada,
        date,
        time,
        local_team,
        visitor_team,
        court,
        result,
        category,
        created_at,
        updated_at
    )
VALUES -- Jornada 1
    (
        1,
        '2025-11-29',
        NULL,
        'DESCANSA',
        'VOLEY MAXORATA',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        1,
        '2025-11-29',
        NULL,
        'CD SIDEOUT',
        'ICOREN',
        NULL,
        '3-0',
        'female',
        NOW(),
        NOW()
    ),
    (
        1,
        '2025-11-29',
        NULL,
        'BRAVEHEART GC',
        'NET 7 BLACKBOARD',
        NULL,
        '2-1',
        'female',
        NOW(),
        NOW()
    ),
    -- Jornada 2
    (
        2,
        '2025-12-13',
        NULL,
        'DESCANSA',
        'BRAVEHEART GC',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        2,
        '2025-12-13',
        NULL,
        'VOLEY MAXORATA',
        'ICOREN',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        2,
        '2025-12-13',
        NULL,
        'NET 7 BLACKBOARD',
        'CD SIDEOUT',
        'Alcaravaneras',
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    -- Jornada 3
    (
        3,
        '2026-01-10',
        NULL,
        'NET 7 BLACKBOARD',
        'CD SIDEOUT',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        3,
        '2026-01-10',
        NULL,
        'BRAVEHEART GC',
        'VOLEY MAXORATA',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        3,
        '2026-01-10',
        NULL,
        'CD SIDEOUT',
        'DESCANSA',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    -- Jornada 4
    (
        4,
        '2026-01-24',
        NULL,
        'BRAVEHEART GC',
        'CD SIDEOUT',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        4,
        '2026-01-24',
        NULL,
        'NET 7 BLACKBOARD',
        'VOLEY MAXORATA',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        4,
        '2026-01-24',
        NULL,
        'DESCANSA',
        'ICOREN',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    -- Jornada 5
    (
        5,
        '2026-02-14',
        NULL,
        'VOLEY MAXORATA',
        'CD SIDEOUT',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        5,
        '2026-02-14',
        NULL,
        'ICOREN',
        'BRAVEHEART GC',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        5,
        '2026-02-14',
        NULL,
        'DESCANSA',
        'NET 7 BLACKBOARD',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    -- Jornada 6
    (
        6,
        '2026-02-28',
        NULL,
        'VOLEY MAXORATA',
        'DESCANSA',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        6,
        '2026-02-28',
        NULL,
        'ICOREN',
        'CD SIDEOUT',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        6,
        '2026-02-28',
        NULL,
        'BRAVEHEART GC',
        'NET 7 BLACKBOARD',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    -- Jornada 7
    (
        7,
        '2026-03-07',
        NULL,
        'DESCANSA',
        'BRAVEHEART GC',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        7,
        '2026-03-07',
        NULL,
        'ICOREN',
        'VOLEY MAXORATA',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        7,
        '2026-03-07',
        NULL,
        'CD SIDEOUT',
        'NET 7 BLACKBOARD',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    -- Jornada 8
    (
        8,
        '2026-03-21',
        NULL,
        'DESCANSA',
        'CD SIDEOUT',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        8,
        '2026-03-21',
        NULL,
        'BRAVEHEART GC',
        'VOLEY MAXORATA',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        8,
        '2026-03-21',
        NULL,
        'NET 7 BLACKBOARD',
        'ICOREN',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    -- Jornada 9
    (
        9,
        '2026-03-28',
        NULL,
        'DESCANSA',
        'ICOREN',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        9,
        '2026-03-28',
        NULL,
        'CD SIDEOUT',
        'BRAVEHEART GC',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        9,
        '2026-03-28',
        NULL,
        'VOLEY MAXORATA',
        'NET 7 BLACKBOARD',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    -- Jornada 10
    (
        10,
        '2026-04-11',
        NULL,
        'DESCANSA',
        'NET 7 BLACKBOARD',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        10,
        '2026-04-11',
        NULL,
        'BRAVEHEART GC',
        'ICOREN',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    ),
    (
        10,
        '2026-04-11',
        NULL,
        'VOLEY MAXORATA',
        'CD SIDEOUT',
        NULL,
        NULL,
        'female',
        NOW(),
        NOW()
    );